<a href="https://colab.research.google.com/github/krakowiakpawel9/ml_course/blob/master/ul/07_pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Wizualizacja danych](#2)
4. [Algorytm K-średnich](#3)
5. [Wizualizacja klastrów](#4)




### <a name='0'></a> Import bibliotek

In [0]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()
np.random.seed(42)
np.set_printoptions(precision=6, suppress=True)

In [2]:
raw_data = load_iris()
all_data = raw_data.copy()
all_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
df = pd.DataFrame(data=np.c_[all_data['data'], all_data['target']], columns=all_data['feature_names'] + ['target'])
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2     0.0
1                4.9               3.0  ...               0.2     0.0
2                4.7               3.2  ...               0.2     0.0
3                4.6               3.1  ...               0.2     0.0
4                5.0               3.6  ...               0.2     0.0

[5 rows x 5 columns]

In [4]:
data = df.iloc[:, :4]
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data = scaler.fit_transform(data)
data[:10]

array([[-0.900681,  1.019004, -1.340227, -1.315444],
       [-1.143017, -0.131979, -1.340227, -1.315444],
       [-1.385353,  0.328414, -1.397064, -1.315444],
       [-1.506521,  0.098217, -1.283389, -1.315444],
       [-1.021849,  1.249201, -1.340227, -1.315444],
       [-0.537178,  1.939791, -1.169714, -1.05218 ],
       [-1.506521,  0.788808, -1.340227, -1.183812],
       [-1.021849,  0.788808, -1.283389, -1.315444],
       [-1.748856, -0.362176, -1.340227, -1.315444],
       [-1.143017,  0.098217, -1.283389, -1.447076]])

In [6]:
from sklearn.decomposition import PCA

pca = PCA(random_state=42)
pca.fit_transform(data)

array([[-2.264703,  0.480027, -0.127706, -0.024168],
       [-2.080961, -0.674134, -0.234609, -0.103007],
       [-2.364229, -0.341908,  0.044201, -0.028377],
       [-2.299384, -0.597395,  0.09129 ,  0.065956],
       [-2.389842,  0.646835,  0.015738,  0.035923],
       [-2.075631,  1.489178,  0.026968, -0.006608],
       [-2.444029,  0.047644,  0.33547 ,  0.036776],
       [-2.232847,  0.223148, -0.088695,  0.024612],
       [-2.33464 , -1.115328,  0.145077,  0.026859],
       [-2.184328, -0.469014, -0.253766,  0.039899],
       [-2.16631 ,  1.043691, -0.268681, -0.016731],
       [-2.326131,  0.133078,  0.093759,  0.133483],
       [-2.218451, -0.728676, -0.230911, -0.002425],
       [-2.633101, -0.961507,  0.180796,  0.019216],
       [-2.198741,  1.860057, -0.472901, -0.194732],
       [-2.262215,  2.686284,  0.030527, -0.050534],
       [-2.207588,  1.483609, -0.005344, -0.188817],
       [-2.19035 ,  0.488838, -0.044215, -0.09309 ],
       [-1.898572,  1.405019, -0.374343, -0.06

In [7]:
pca.explained_variance_ratio_

array([0.729624, 0.228508, 0.036689, 0.005179])

In [8]:
explained_variance = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
explained_variance = explained_variance.reset_index().rename(columns={'index': 'principal_component'})
explained_variance

principal_component  explained_variance_ratio
0                    0                  0.729624
1                    1                  0.228508
2                    2                  0.036689
3                    3                  0.005179

In [9]:
import plotly.express as px

px.bar(explained_variance, x='principal_component', y='explained_variance_ratio', width=700, height=400)

In [10]:
pca = PCA(n_components=2, random_state=42)
data_pca_2 = pca.fit_transform(data)
data_pca_2

array([[-2.264703,  0.480027],
       [-2.080961, -0.674134],
       [-2.364229, -0.341908],
       [-2.299384, -0.597395],
       [-2.389842,  0.646835],
       [-2.075631,  1.489178],
       [-2.444029,  0.047644],
       [-2.232847,  0.223148],
       [-2.33464 , -1.115328],
       [-2.184328, -0.469014],
       [-2.16631 ,  1.043691],
       [-2.326131,  0.133078],
       [-2.218451, -0.728676],
       [-2.633101, -0.961507],
       [-2.198741,  1.860057],
       [-2.262215,  2.686284],
       [-2.207588,  1.483609],
       [-2.19035 ,  0.488838],
       [-1.898572,  1.405019],
       [-2.343369,  1.127849],
       [-1.914323,  0.408856],
       [-2.207013,  0.924121],
       [-2.774345,  0.458344],
       [-1.81867 ,  0.085559],
       [-2.227163,  0.137254],
       [-1.951846, -0.625619],
       [-2.051151,  0.242164],
       [-2.168577,  0.52715 ],
       [-2.139563,  0.313218],
       [-2.265261, -0.337732],
       [-2.140122, -0.504541],
       [-1.831595,  0.423695],
       [

In [11]:
pca.explained_variance_ratio_

array([0.729624, 0.228508])

In [12]:
df['target']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64

In [13]:
data_pca = pd.DataFrame(data={'pca_1': data_pca_2[:, 0], 'pca_2': data_pca_2[:, 1], 'target': df['target']})
data_pca

pca_1     pca_2  target
0   -2.264703  0.480027     0.0
1   -2.080961 -0.674134     0.0
2   -2.364229 -0.341908     0.0
3   -2.299384 -0.597395     0.0
4   -2.389842  0.646835     0.0
..        ...       ...     ...
145  1.870503  0.386966     2.0
146  1.564580 -0.896687     2.0
147  1.521170  0.269069     2.0
148  1.372788  1.011254     2.0
149  0.960656 -0.024332     2.0

[150 rows x 3 columns]

In [14]:
px.scatter(data_pca, x='pca_1', y='pca_2', color='target', width=700, height=500, color_continuous_midpoint=1.2)

In [17]:
pca = PCA(n_components=0.97, random_state=42)
data_pca = pca.fit_transform(data)
data_pca

array([[-2.264703,  0.480027, -0.127706],
       [-2.080961, -0.674134, -0.234609],
       [-2.364229, -0.341908,  0.044201],
       [-2.299384, -0.597395,  0.09129 ],
       [-2.389842,  0.646835,  0.015738],
       [-2.075631,  1.489178,  0.026968],
       [-2.444029,  0.047644,  0.33547 ],
       [-2.232847,  0.223148, -0.088695],
       [-2.33464 , -1.115328,  0.145077],
       [-2.184328, -0.469014, -0.253766],
       [-2.16631 ,  1.043691, -0.268681],
       [-2.326131,  0.133078,  0.093759],
       [-2.218451, -0.728676, -0.230911],
       [-2.633101, -0.961507,  0.180796],
       [-2.198741,  1.860057, -0.472901],
       [-2.262215,  2.686284,  0.030527],
       [-2.207588,  1.483609, -0.005344],
       [-2.19035 ,  0.488838, -0.044215],
       [-1.898572,  1.405019, -0.374343],
       [-2.343369,  1.127849,  0.13263 ],
       [-1.914323,  0.408856, -0.421293],
       [-2.207013,  0.924121,  0.159865],
       [-2.774345,  0.458344,  0.332179],
       [-1.81867 ,  0.085559,  0.0

In [19]:
data_pca_3d = pd.DataFrame(data={'pca_1': data_pca[:, 0], 'pca_2': data_pca[:, 1], 'pca_3': data_pca[:, 2], 'target': df['target']})
data_pca_3d

pca_1     pca_2     pca_3  target
0   -2.264703  0.480027 -0.127706     0.0
1   -2.080961 -0.674134 -0.234609     0.0
2   -2.364229 -0.341908  0.044201     0.0
3   -2.299384 -0.597395  0.091290     0.0
4   -2.389842  0.646835  0.015738     0.0
..        ...       ...       ...     ...
145  1.870503  0.386966  0.256274     2.0
146  1.564580 -0.896687 -0.026371     2.0
147  1.521170  0.269069  0.180178     2.0
148  1.372788  1.011254  0.933395     2.0
149  0.960656 -0.024332  0.528249     2.0

[150 rows x 4 columns]

In [24]:
px.scatter_3d(data_pca_3d, x='pca_1', y='pca_2', z='pca_3', color='target', symbol='target', opacity=0.7, width=700)