<a href="https://colab.research.google.com/github/krakowiakpawel9/ml_course/blob/master/basic/03_text_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Wektoryzacja tekstu](#2)
4. [Wektoryzacja tekstu - bigramy](#3)
5. [TFIDF Transformer](#4)
6. [TFIDF Vectorizer](#5)
7. [Przygotowanie danych tekstowych - przykład](#6)



### <a name='0'></a> Import bibliotek

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True, edgeitems=10, linewidth=1000, formatter=dict(float=lambda x: f'{x:.2f}'))
sklearn.__version__

'0.22.1'

### <a name='1'></a> Wygenerowanie danych

In [3]:
documents = [
    'Hello world',
    'Hello',
    'I am going to say: hello.',
    'Beautiful world!!!'
]

print(documents)

['Hello world', 'Hello', 'I am going to say: hello.', 'Beautiful world!!!']


### <a name='2'></a> Wektoryzacja tekstu

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit_transform(documents)

<4x7 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [5]:
vectorizer.fit_transform(documents).toarray()

array([[0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 1]])

In [7]:
vectorizer.get_feature_names()

['am', 'beautiful', 'going', 'hello', 'say', 'to', 'world']

In [8]:
df = pd.DataFrame(data=vectorizer.fit_transform(documents).toarray(), 
                  columns=vectorizer.get_feature_names())

df

am  beautiful  going  hello  say  to  world
0   0          0      0      1    0   0      1
1   0          0      0      1    0   0      0
2   1          0      1      1    1   1      0
3   0          1      0      0    0   0      1

In [9]:
vectorizer.vocabulary_

{'am': 0,
 'beautiful': 1,
 'going': 2,
 'hello': 3,
 'say': 4,
 'to': 5,
 'world': 6}

In [11]:
vectorizer.transform(['Say: hello!']).toarray()

array([[0, 0, 0, 1, 1, 0, 0]])

### <a name='3'></a> Wektoryzacja tekstu - bigramy

In [12]:
bigram = CountVectorizer(ngram_range=(1, 2), min_df=1)    # min_df=2
bigram.fit_transform(documents).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [13]:
bigram.vocabulary_

{'am': 0,
 'am going': 1,
 'beautiful': 2,
 'beautiful world': 3,
 'going': 4,
 'going to': 5,
 'hello': 6,
 'hello world': 7,
 'say': 8,
 'say hello': 9,
 'to': 10,
 'to say': 11,
 'world': 12}

In [14]:
df = pd.DataFrame(data=bigram.fit_transform(documents).toarray(), 
                  columns=bigram.get_feature_names())
df

am  am going  beautiful  beautiful world  ...  say hello  to  to say  world
0   0         0          0                0  ...          0   0       0      1
1   0         0          0                0  ...          0   0       0      0
2   1         1          0                0  ...          1   1       1      0
3   0         0          1                1  ...          0   0       0      1

[4 rows x 13 columns]

### <a name='4'></a> TFIDF Transformer

In [16]:
documents = [
    'Hello world',
    'Hello',
    'I am going to say: hello.',
    'Beautiful world!!!'
]

print(documents)

['Hello world', 'Hello', 'I am going to say: hello.', 'Beautiful world!!!']


In [17]:
counts = vectorizer.fit_transform(documents).toarray()
counts

array([[0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 1]])

In [18]:
df = pd.DataFrame(data=vectorizer.fit_transform(documents).toarray(), columns=vectorizer.get_feature_names())
df

am  beautiful  going  hello  say  to  world
0   0          0      0      1    0   0      1
1   0          0      0      1    0   0      0
2   1          0      1      1    1   1      0
3   0          1      0      0    0   0      1

In [19]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer()
tfidf.fit_transform(counts).toarray()

array([[0.00, 0.00, 0.00, 0.63, 0.00, 0.00, 0.78],
       [0.00, 0.00, 0.00, 1.00, 0.00, 0.00, 0.00],
       [0.48, 0.00, 0.48, 0.30, 0.48, 0.48, 0.00],
       [0.00, 0.79, 0.00, 0.00, 0.00, 0.00, 0.62]])

### <a name='5'></a> TFIDF Vectorizer

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit_transform(documents).toarray()

array([[0.00, 0.00, 0.00, 0.63, 0.00, 0.00, 0.78],
       [0.00, 0.00, 0.00, 1.00, 0.00, 0.00, 0.00],
       [0.48, 0.00, 0.48, 0.30, 0.48, 0.48, 0.00],
       [0.00, 0.79, 0.00, 0.00, 0.00, 0.00, 0.62]])

In [21]:
tfidf_vectorizer.idf_

array([1.92, 1.92, 1.92, 1.22, 1.92, 1.92, 1.51])