<a href="https://colab.research.google.com/github/krakowiakpawel9/ml_course/blob/master/basic/05_tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### nltk
Strona biblioteki: [https://www.nltk.org/](https://www.nltk.org/)  

Podstawowa biblioteka do przetwarzania języka naturalnego w języku Python.

Aby zainstalować bibliotekę nltk, użyj polecenia poniżej:
```
!pip install nltk
```
Aby zaktualizować do najnowszej wersji użyj polecenia poniżej:
```
!pip install --upgrade nltk
```
Kurs stworzony w oparciu o wersję `3.2.5`

### Spis treści:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)



### <a name='0'></a> Import bibliotek

In [0]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [82]:
docs = [
    'step 1: get the data',
    'step 2: preprocess the data',
    'step 3: analyze the data',
    'step 4: build a model',
    'step 5: deploy the model'
]

vectorizer = CountVectorizer()
docs_vec = vectorizer.fit_transform(docs)
docs_vec

<5x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [83]:
docs_vec.toarray()

array([[0, 0, 1, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 1]])

In [90]:
df = pd.DataFrame(data=docs_vec.toarray(), columns=vectorizer.get_feature_names())
df

analyze  build  data  deploy  get  model  preprocess  step  the
0        0      0     1       0    1      0           0     1    1
1        0      0     1       0    0      0           1     1    1
2        1      0     1       0    0      0           0     1    1
3        0      1     0       0    0      1           0     1    0
4        0      0     0       1    0      1           0     1    1

In [94]:
tfidf = TfidfVectorizer()

docs_tfidf = tfidf.fit_transform(docs)
docs_tfidf

<5x9 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [95]:
docs_tfidf.toarray()

array([[0.    , 0.    , 0.4744, 0.    , 0.7084, 0.    , 0.    , 0.3375, 0.3991],
       [0.    , 0.    , 0.4744, 0.    , 0.    , 0.    , 0.7084, 0.3375, 0.3991],
       [0.7084, 0.    , 0.4744, 0.    , 0.    , 0.    , 0.    , 0.3375, 0.3991],
       [0.    , 0.7297, 0.    , 0.    , 0.    , 0.5887, 0.    , 0.3477, 0.    ],
       [0.    , 0.    , 0.    , 0.6749, 0.    , 0.5445, 0.    , 0.3216, 0.3802]])

In [104]:
df = pd.DataFrame(data=docs_tfidf.toarray(), columns=tfidf.get_feature_names())
df

analyze     build      data  ...  preprocess      step       the
0  0.000000  0.000000  0.474392  ...    0.000000  0.337534  0.399074
1  0.000000  0.000000  0.474392  ...    0.708353  0.337534  0.399074
2  0.708353  0.000000  0.474392  ...    0.000000  0.337534  0.399074
3  0.000000  0.729718  0.000000  ...    0.000000  0.347715  0.000000
4  0.000000  0.000000  0.000000  ...    0.000000  0.321598  0.380232

[5 rows x 9 columns]

In [98]:
tfidf.idf_

array([2.0986, 2.0986, 1.4055, 2.0986, 2.0986, 1.6931, 2.0986, 1.    , 1.1823])

In [103]:
df_weights = pd.DataFrame(data=tfidf.idf_, index=tfidf.get_feature_names(), columns=['idf_weights'])
df_weights

idf_weights
analyze        2.098612
build          2.098612
data           1.405465
deploy         2.098612
get            2.098612
model          1.693147
preprocess     2.098612
step           1.000000
the            1.182322

In [111]:
df.iloc[0, :].sort_values(ascending=False)

get           0.708353
data          0.474392
the           0.399074
step          0.337534
preprocess    0.000000
model         0.000000
deploy        0.000000
build         0.000000
analyze       0.000000
Name: 0, dtype: float64

In [112]:
docs[0]

'step 1: get the data'