<a href="https://colab.research.google.com/github/krakowiakpawel9/ml_course/blob/master/cont/04_linear_regression_gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn  
Website: [https://scikit-learn.org/](https://scikit-learn.org/)

### Metoda gradientu

In [0]:
# !pip install --upgrade scikit-learn

In [0]:
import numpy as np

In [3]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(X1)
print(Y)
print(m)

[1 2 3 4 5 6]
[3000 3250 3500 3750 4000 4250]
6


In [4]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [5]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [6]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [7]:
eta = 0.01
m = len(X)

weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 1.66466192]
 [-2.26760586]]


In [8]:
weights - eta * (2 / m) * X.T.dot(X.dot(weights) - Y)

array([[ 74.29010109],
       [266.63704158]])

In [9]:
for i in range(2000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient

print(weights)

[[2748.29813142]
 [ 250.39752153]]
