<a href="https://colab.research.google.com/github/krakowiakpawel9/ml_course/blob/master/cont/15_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn  
Website: [https://scikit-learn.org/](https://scikit-learn.org/)

In [0]:
# !pip install --upgrade scikit-learn

In [1]:
import numpy as np
import pandas as pd
import sklearn
sklearn.__version__

'0.21.3'

In [0]:
pogoda = ['słonecznie', 'deszczowo', 'pochmurno', 'deszczowo', 'słonecznie', 'słonecznie',
          'pochmurno', 'pochmurno', 'słonecznie']
temperatura = ['ciepło', 'zimno', 'ciepło', 'ciepło', 'ciepło', 'umiarkowanie',
               'umiarkowanie', 'ciepło', 'zimno']

spacer = ['tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie']               

In [0]:
from sklearn.preprocessing import LabelEncoder

le_pogoda = LabelEncoder()
pogoda_encoded = le_pogoda.fit_transform(pogoda)

le_temperatura = LabelEncoder()
temperatura_encoded = le_temperatura.fit_transform(temperatura)

le_spacer = LabelEncoder()
spacer_encoded = le_spacer.fit_transform(spacer)

In [9]:
pogoda_encoded

array([2, 0, 1, 0, 2, 2, 1, 1, 2])

In [10]:
temperatura_encoded

array([0, 2, 0, 0, 0, 1, 1, 0, 2])

In [12]:
spacer_encoded

array([1, 0, 1, 0, 1, 1, 0, 1, 0])

In [0]:
data = list(zip(pogoda_encoded, temperatura_encoded))
target = spacer_encoded

In [16]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(data, target)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
model.predict([(2, 0)])

array([1])

In [19]:
model.predict_proba([(2, 0)])

array([[0.03582272, 0.96417728]])